apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-demo-serv-logconfig
  namespace: dave-demo-services
data:
{{- range $path, $fileContents := .Files.Glob "configs/logback-spring.xml" }}
    logback-spring.xml: |
      {{- $fileContents | nindent 4 }}
{{- end }}
