{{ $appname := .Chart.Name }}
{{ $namespace := $.Values.nameSpace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-demo-serv-logconfig
  namespace: {{ $namespace }}
data:
  logback-spring.xml: |
{{ (.Files.Glob "configs/logback-spring.xml").AsConfig | indent 2 }}
