server:
  port: 8888
spring:
  application:
    name: configserver
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wiseass33/dave-demo-props
          default-label: development
          search-paths:
            - "/app-config"            # Global application.yaml; changed double quotes to single quotes
            - "/app-config/common"     # Global per-service configs; changed double quotes to single quotes
            - "/app-config/dev"        # Per-service, per-environment configs; changed double quotes to single quotes
          cloneOnStart: true         # Clone the repositories at startup.
    bus:
      enabled: true  #Changed to "false"" Sunday envening from "true""; no difference so changed back to "true"."
      id: my-configserver-bus
    stream:
      bindings:
        refreshIn:
          destination: configRefreshQueue
        refreshOut:
          destination: configRefreshQueue
          group: dave-demo-service
          content-type: application/json
          binder: rabbit
  rabbitmq:
    host: rabbitmq #Set to "localhost"" for local testing and "rabbitmq" for k3s.
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
