server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wiseass33/dave-demo-props
          default-label: development
          search-paths:
            - "/"                   # Global application.yaml
            - "{application}"        # Global per-service configs
            - "{profile}"            # Per-environment configs (Dev, QA, etc.)
            - "{profile}/{application}"  # Per-service, per-environment configs
          cloneOnStart: true
    bus:
      enabled: true
      id: my-configserver-bus
    stream:
      bindings:
        refreshIn:
          destination: configRefreshQueue
        refreshOut:
          destination: configRefreshQueue
          group: dave-demo-service
          content-type: application/json
          binder: rabbit
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
