{{- if not (lookup "v1" "Service" $.Values.nameSpace $.Values.service.istioServiceName) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.istioServiceName }}
  labels:
    app: configserver
    istio-injection: enabled
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: configserver