apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app: configserver
    istio-injection: enabled
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: configserver