name: CD - Deploy to DEV OCP

on:
  workflow_call:
    inputs:
      runner_name:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      environment_value:
        required: true
        type: string
      env_vars_file:
        required: true
        type: string
    secrets:
      DEV_SA_TOKEN:
        required: false

jobs:
  deploy-dev: 
    name: Deploy-${{ inputs.environment_value }}
    environment: ${{ inputs.environment_value }}
    runs-on: ${{ inputs.runner_name }}
    permissions:
      contents: 'write'
      pull-requests: 'write'
      id-token: 'write'      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: DotEnv action variables
      uses: xom9ikk/dotenv@v2.3.0
      with:
        path: ./ghactions-envvars
        mode: ${{ inputs.env_vars_file }}
    - name: Set up Environment DEV
      if: ${{ inputs.environment_value == 'dev' }}
      run: |
          echo NAMESPACE=${{ env.OPENSHIFT_PROJECT_NAME_DEV }} >> $GITHUB_ENV
          echo values_file=dev-values.yaml >> $GITHUB_ENV
          echo SA_TOKEN=${{ secrets.K3S_API_TOKEN }} >> $GITHUB_ENV
    - name: Debug API Token
      run: |
        if [ -z "${{ secrets.K3S_API_TOKEN }}" ]; then
          echo "K3S_API_TOKEN is empty!"
          exit 1
        else
          echo "K3S_API_TOKEN is set (masked output)"
        fi
    - name: Authenticate with K3s
      run: |
          kubectl config set-cluster k3s-cluster --server=https://${{ secrets.K3S_SERVER_IP }}:6443 --insecure-skip-tls-verify=true
          kubectl config set-credentials github-actions --token=${{ secrets.K3S_API_TOKEN }}
          kubectl config set-context k3s --cluster=k3s-cluster --user=github-actions
          kubectl config use-context k3s
    - name: Test K3s Connection
      run: |
          kubectl get nodes
          kubectl auth can-i '*' '*' --all-namespaces
    - name: K3s App Deployment
      run: |
        helm version	
        helm upgrade --install ${{ env.APPLICATION_NAME }} \
        -f ${{ env.PROJECT_FOLDER_NAME }}/helm/${{ env.APPLICATION_NAME }}/env-values/${{ env.values_file }} \
        ./${{ env.PROJECT_FOLDER_NAME }}/helm/${{ env.APPLICATION_NAME }} \
        --set nameSpace=$NAMESPACE \
        --namespace $NAMESPACE \
        --history-max 3 \
        --set imagePullSecrets[0].name=ghcr-secret \
        --set app.version=1 \
        --set app.name=${{ env.APPLICATION_NAME }} \
        --set image.tag=${{ inputs.IMAGE_TAG }}