name: Eureka Server CICD Workflow .
run-name: eurekaserver Pipeline
on:
  workflow_dispatch:  

jobs:
  get_runners_details:
    name: Fetch Runner Details
    uses: wiseass33/dave-k3s-cluster-demo/.github/workflows/fetch_runner_details.yaml
    secrets: inherit
