name: Platform Eureka Server CICD Workflow .
run-name: platformeurekaserver Pipeline
on:
  workflow_dispatch:  

jobs:
  get_runners_details:
    name: Fetch Runner Details
    uses: ./.github/workflows/fetch_runner_details.yml
    secrets: inherit
